// @vitest-environment happy-dom
import { test, expect, afterEach, vi } from 'vitest'
import Character from '../src/character.js'
import Game from '../src/game.js';

afterEach(() => {
    document.body.innerHTML = ''
})

// 게임 초기화
test('게임이 초기화되면 document body에 루트 DOM이 붙는다', () => {
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    expect(document.body.querySelector<HTMLDivElement>('#mini-game-root')).not.toBeNull()
})

test('초기화하기 전에 렌더하면 에러를 던진다', () => {
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    expect(() => game.render()).toThrow(new Error('초기화해 주세요'))
})

test('게임이 초기화되면 화면에 캐릭터가 표시된다', () => {
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    expect(root.querySelector<HTMLDivElement>('#character')).not.toBeNull()
})

test('게임이 초기화되면 화면에 허들이 표시된다', () => {
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    expect(root.querySelector<HTMLDivElement>('#hurdle')).not.toBeNull()
})

test('게임이 초기화되면 화면에 시작 버튼이 표시된다', () => {
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    expect(root.querySelector<HTMLButtonElement>('#startButton')).not.toBeNull()
})

// 게임 동작
test('시작 버튼을 누르면 게임이 시작된다', () => {
    vi.useFakeTimers()
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    expect(game.requestAnimationFrameId).toBeNull()
    const startButton = document.querySelector<HTMLButtonElement>('#startButton')
    startButton?.click()
    vi.advanceTimersToNextFrame()
    expect(game.requestAnimationFrameId).not.toBeNull()
    vi.useRealTimers()
})

test('종료 버튼을 누르면 게임이 종료된다', () => {
    vi.useFakeTimers()
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    const startButton = document.querySelector<HTMLButtonElement>('#startButton')
    startButton?.click()
    vi.advanceTimersToNextFrame()
    expect(game.requestAnimationFrameId).not.toBeNull()
    const stopButton = document.querySelector<HTMLButtonElement>('#stopButton')
    stopButton?.click()
    vi.advanceTimersToNextFrame()
    expect(game.requestAnimationFrameId).toBeNull()
    vi.useRealTimers()
})

test('중단 버튼을 누르면 게임이 중단된다', () => {
    vi.useFakeTimers()
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    const startButton = document.querySelector<HTMLButtonElement>('#startButton')
    startButton?.click()
    vi.advanceTimersToNextFrame()
    expect(game.isPaused).toBe(false)
    const pauseButton = document.querySelector<HTMLButtonElement>('#pauseButton')
    pauseButton?.click()
    vi.advanceTimersToNextFrame()
    expect(game.isPaused).toBe(true)
    vi.useRealTimers()
})

test('재개 버튼을 누르면 게임이 재개된다', () => {
    vi.useFakeTimers()
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    const startButton = document.querySelector<HTMLButtonElement>('#startButton')
    startButton?.click()
    const pauseButton = document.querySelector<HTMLButtonElement>('#pauseButton')
    pauseButton?.click()
    vi.advanceTimersToNextFrame()
    expect(game.isPaused).toBe(true)
    const resumeButton = document.querySelector<HTMLButtonElement>('#resumeButton')
    resumeButton?.click()
    vi.advanceTimersToNextFrame()
    expect(game.isPaused).toBe(false)
    vi.useRealTimers()
})

test('캐릭터가 점프하면 발이 올라가 보인다', () => {
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    character.jump()
    game.render()
    expect(root.querySelector<HTMLDivElement>('#character')?.style.bottom).toBe(Character.JUMP_HEIGHT + 'px')
    character.jump()
    game.render()
    expect(root.querySelector<HTMLDivElement>('#character')?.style.bottom).toBe(Character.JUMP_HEIGHT * 2 + 'px')
})

test('시간이 지날수록 허들이 왼쪽으로 이동되어 보인다', () => {
    vi.useFakeTimers()
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    game.start()
    vi.advanceTimersToNextFrame()
    const beforeLeft = parseFloat(root.querySelector<HTMLDivElement>('#hurdle')?.style.left ?? '0')
    vi.advanceTimersToNextFrame()
    const afterLeft = parseFloat(root.querySelector<HTMLDivElement>('#hurdle')?.style.left ?? '0')
    expect(afterLeft).toBeLessThan(beforeLeft)
    game.stop()
    vi.useRealTimers()
})

test('점프 버튼을 누르면 캐릭터가 점프한다', () => {
    vi.useFakeTimers()
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    const startButton = document.querySelector<HTMLButtonElement>('#startButton')
    startButton?.click()
    const jumpButton = document.querySelector<HTMLButtonElement>('#jumpButton')
    jumpButton?.click()
    vi.advanceTimersToNextFrame()
    expect(root.querySelector<HTMLDivElement>('#character')?.style.bottom).toBe(Character.JUMP_HEIGHT + 'px')
    jumpButton?.click()
    vi.advanceTimersToNextFrame()
    expect(root.querySelector<HTMLDivElement>('#character')?.style.bottom).toBe(Character.JUMP_HEIGHT * 2 + 'px')
})

// 비주얼
test('시작 버튼을 누르면 화면에 점프 버튼이 표시된다', () => {
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    expect(root.querySelector<HTMLButtonElement>('#jumpButton')).toBeNull()
    const startButton = document.querySelector<HTMLButtonElement>('#startButton')
    startButton?.click()
    expect(root.querySelector<HTMLButtonElement>('#jumpButton')).not.toBeNull()
})

test('시작 버튼을 누르면 화면에 종료 버튼이 표시된다', () => {
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    expect(root.querySelector<HTMLButtonElement>('#stopButton')).toBeNull()
    const startButton = document.querySelector<HTMLButtonElement>('#startButton')
    startButton?.click()
    expect(root.querySelector<HTMLButtonElement>('#stopButton')).not.toBeNull()
})

test('시작 버튼을 누르면 화면에 중단 버튼이 표시된다', () => {
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    expect(root.querySelector<HTMLButtonElement>('#pauseButton')).toBeNull()
    const startButton = document.querySelector<HTMLButtonElement>('#startButton')
    startButton?.click()
    expect(root.querySelector<HTMLButtonElement>('#pauseButton')).not.toBeNull()
})

test('시작 버튼을 누르면 화면에 시작 버튼이 사라진다', () => {
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    expect(root.querySelector<HTMLButtonElement>('#startButton')?.style.display).not.toBe('none')
    const startButton = document.querySelector<HTMLButtonElement>('#startButton')
    startButton?.click()
    expect(root.querySelector<HTMLButtonElement>('#startButton')?.style.display).toBe('none')
})

test('중단 버튼을 누르면 화면에 재개 버튼이 표시된다', () => {
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    const startButton = document.querySelector<HTMLButtonElement>('#startButton')
    startButton?.click()
    expect(root.querySelector<HTMLButtonElement>('#resumeButton')).toBeNull()
    const pauseButton = document.querySelector<HTMLButtonElement>('#pauseButton')
    pauseButton?.click()
    expect(root.querySelector<HTMLButtonElement>('#resumeButton')).not.toBeNull()
})

test('중단 버튼을 누르면 화면에 중단 버튼이 사라진다', () => {
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    const startButton = document.querySelector<HTMLButtonElement>('#startButton')
    startButton?.click()
    expect(root.querySelector<HTMLButtonElement>('#pauseButton')?.style.display).not.toBe('none')
    const pauseButton = document.querySelector<HTMLButtonElement>('#pauseButton')
    pauseButton?.click()
    expect(root.querySelector<HTMLButtonElement>('#pauseButton')?.style.display).toBe('none')
})

test('재개 버튼을 누르면 화면에 재개 버튼이 사라지고 중단 버튼이 표시된다', () => {
    const root = document.createElement('div')
    const character = new Character()
    const game = new Game(root, character)
    game.init()
    const startButton = document.querySelector<HTMLButtonElement>('#startButton')
    startButton?.click()
    const pauseButton = document.querySelector<HTMLButtonElement>('#pauseButton')
    pauseButton?.click()
    expect(root.querySelector<HTMLButtonElement>('#resumeButton')?.style.display).not.toBe('none')
    expect(root.querySelector<HTMLButtonElement>('#pauseButton')?.style.display).toBe('none')
    const resumeButton = document.querySelector<HTMLButtonElement>('#resumeButton')
    resumeButton?.click()
    expect(root.querySelector<HTMLButtonElement>('#resumeButton')?.style.display).toBe('none')
    expect(root.querySelector<HTMLButtonElement>('#pauseButton')?.style.display).not.toBe('none')
})
